export const clerkAppearance = {
  layout: {
    socialButtonsPlacement: "top" as const,
    showOptionalFields: true,
  },
  variables: {
    colorPrimary: "#0d5c63",
    colorBackground: "#fbf8f3",
    colorInputBackground: "#fffdf9",
    colorInputText: "#17130f",
    colorText: "#17130f",
    colorTextSecondary: "#5f574f",
    colorTextOnPrimaryBackground: "#f7f4ef",
    colorDanger: "#8f2f2a",
    colorSuccess: "#24553a",
    colorWarning: "#8a4d12",
    colorNeutral: "#8a8178",
    colorShimmer: "#efe8dd",
    borderRadius: "1rem",
    fontFamily: "var(--font-geist-sans), system-ui, sans-serif",
    fontFamilyButtons: "var(--font-geist-sans), system-ui, sans-serif",
    fontSize: "0.9375rem",
  },
  elements: {
    rootBox: "mx-auto h-auto w-full max-w-[440px]",
    cardBox: "mx-auto h-auto min-h-0 w-full max-w-[440px] bg-transparent shadow-none",
    card: "h-auto w-full rounded-[1.25rem] border border-[var(--border)] bg-[var(--surface-elevated)] p-6 shadow-[var(--shadow-elevated)] sm:p-7",
    scrollBox: "h-auto overflow-visible bg-transparent",
    page: "h-auto bg-transparent",
    main: "gap-4",
    header: "gap-2",
    headerTitle: "font-display text-2xl tracking-tight text-[var(--foreground)]",
    headerSubtitle: "text-sm text-[var(--foreground-secondary)]",
    socialButtons: "gap-3",
    socialButtonsBlockButton:
      "h-11 rounded-full border border-[var(--border)] bg-[var(--surface)] text-[var(--foreground)] shadow-none hover:bg-[var(--surface-hover)]",
    socialButtonsBlockButtonText: "text-[var(--foreground)] font-medium",
    socialButtonsProviderIcon: "opacity-90",
    formButtonPrimary:
      "h-11 rounded-full bg-[var(--accent)] text-[var(--accent-foreground)] shadow-none hover:bg-[var(--accent-hover)] focus-visible:ring-2 focus-visible:ring-[var(--ring)]",
    formFieldInput:
      "rounded-2xl border border-[var(--border)] bg-[var(--surface)] text-[var(--foreground)] shadow-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--ring)]",
    formFieldLabel: "text-[var(--foreground-secondary)]",
    footer: "bg-transparent pt-2",
    footerAction: "justify-center",
    footerActionText: "text-sm text-[var(--foreground-secondary)]",
    footerActionLink: "text-[var(--accent)] hover:text-[var(--accent-hover)]",
    footerPages: "text-xs text-[var(--foreground-muted)] opacity-80",
    footerPagesLink: "text-[var(--foreground-muted)] hover:text-[var(--foreground-secondary)]",
    identityPreviewText: "text-[var(--foreground)]",
    identityPreviewEditButton: "text-[var(--accent)]",
    dividerLine: "bg-[var(--border)]",
    dividerText: "text-xs text-[var(--foreground-muted)]",
    alertText: "text-[var(--foreground-secondary)]",
    formFieldInputShowPasswordButton: "text-[var(--foreground-muted)]",
    navbarButton: "text-[var(--foreground)]",
    profileSectionTitle: "font-display text-[var(--foreground)]",
    profileSectionContent: "text-[var(--foreground-secondary)]",
    userButtonBox: "h-9 w-9",
    userButtonTrigger:
      "flex h-9 w-9 items-center justify-center rounded-full ring-1 ring-[var(--border)]/80 transition hover:ring-[var(--accent)] focus:shadow-none",
    userButtonAvatarBox:
      "h-9 w-9 rounded-full bg-[var(--accent)] text-[var(--accent-foreground)] shadow-none",
    avatarBox: "h-9 w-9 rounded-full",
    userButtonPopoverCard:
      "rounded-2xl border border-[var(--border)] bg-[var(--surface-elevated)] shadow-[var(--shadow-soft)]",
    userButtonPopoverActionButton: "text-[var(--foreground)] hover:bg-[var(--surface-hover)]",
    userButtonPopoverFooter: "hidden",
    badge:
      "rounded-full border border-[var(--border)] bg-[var(--surface-muted)] text-[var(--foreground-muted)]",
  },
};
